var tasks = {
	"data":[
        {id:1, 
         text:"Management", 
         start_date:"22-05-2015", 
         duration:13, 
         progress:0.1, 
         open: true, 
         workers: "Massimo M., Saverio",
         description: "Project management of the Machine Design exercise"},
        {id:2, 
         text:"Gantt",    
         start_date:"22-05-2015", 
         duration:13, 
         progress:0.1, 
         parent:1, 
         workers: "All", 
         description: "Design the Gantt chart for the process"},
        {id:3, 
         text:"Report work",    
         start_date:"24-05-2015", 
         duration:8, 
         progress:0.6, 
         parent:1, 
         workers: "Saverio", 
         description: "Report the status of the teamwork to the instructor"},
        {id:4, 
         text:"Select doc", 
         start_date:"28-05-2015", 
         duration:13, 
         progress:0.1, 
         parent:1, 
         open: true, 
         workers: "Saverio", 
         description: "Select best part of the documentation done by each student"},
        {id:5, 
         text:"Research",    
         start_date:"22-05-2015", 
         duration:8, 
         progress:0.2, 
         workers: "All", 
         description: "Study the [m]MTM + Gestalt framwework"},
        {id:6, 
         text:"Study text",    
         start_date:"22-05-2015", 
         duration:8, 
         progress:0.6, 
         parent:5, 
         workers: "Students", 
         description: "Write a short text+pics of a part of the framework studied"},
        {id:7, 
         text:"Project text",    
         start_date:"22-05-2015", 
         duration:8, 
         progress:0.6, 
         parent:5, 
         workers: "Saverio", 
         description: "Write a short text+pics about the exercise project"},
        {id:8, 
         text:"More...", 
         start_date:"22-05-2015", 
         duration:4, 
         progress:0.1, 
         open: true, 
         workers: "...", 
         description: "..."},
        {id:9, 
         text:"More...", 
         start_date:"22-05-2015", 
         duration:4, 
         progress:0.1, 
         parent: 8,
         open: true, 
         workers: "...", 
         description: "..."},
    ],
    links:[
        { id:1, source:1, target:5, type:"1"},
        { id:2, source:1, target:8, type:"1"},
  ]
}